// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/drum-home/ColdPrecision.tsx": () => import("../components/mockups/drum-home/ColdPrecision.tsx"),
  "./components/mockups/drum-home/RawIndustrial.tsx": () => import("../components/mockups/drum-home/RawIndustrial.tsx"),
  "./components/mockups/drum-home/WarmSignal.tsx": () => import("../components/mockups/drum-home/WarmSignal.tsx")
};
